name: JungleSurvivalCore
version: ${project.version}
main: pl.wolny.junglesurvivalcore.JungleSurvivalCore
api-version: 1.17
authors: [ WcaleNieWolny ]
description: Yes, it is a core. Do not hate me :)
permissions:
  junglesrv.admin:
    description: Allow you to warn other players :)
    default: op
commands:
  warn:
    description: Warn a player
  warns:
    description: See player warns
